spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  # DataSource Config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.100.132:3306/hdfs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

server:
  port: 10001
  servlet:
    context-path: /hdfs


file-store-path: D://opt//upload//



